/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 src/animated/assets/PortfolioCard.glb -t -o src/animated/components/PortfolioCardModel.tsx 
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { useMemo } from 'react'

import modelUrl from '../assets/PortfolioCard.glb?url'

type GLTFResult = GLTF & {
  nodes: {
    Card: THREE.Mesh
    Jason_Poon: THREE.Mesh
    Portfolio: THREE.Mesh
    ['Tri-L1']: THREE.Mesh
    ['Plane-L2']: THREE.Mesh
    ['Plane-L1']: THREE.Mesh
    ['Circle-L1']: THREE.Mesh
    ['Plane-R']: THREE.Mesh
    ['Tri-R']: THREE.Mesh
    ['Tri-R002']: THREE.Mesh
    ['Tri-R003']: THREE.Mesh
    ['Tri-R004']: THREE.Mesh
    ['Plane-R-001']: THREE.Mesh
    ['Tri-R005']: THREE.Mesh
    ['Tri-R-E001']: THREE.Mesh
    ['Tri-R001']: THREE.Mesh
    ['Tri-R006']: THREE.Mesh
    Plane: THREE.Mesh
    BézierCurve002: THREE.Mesh
    BézierCurve002_1: THREE.Mesh
    BézierCurve002_2: THREE.Mesh
    Star: THREE.Mesh
    Plane001: THREE.Mesh
  }
  materials: {
    ['Light Yellow']: THREE.MeshStandardMaterial
    ['Dark Blue']: THREE.MeshStandardMaterial
    Yellow: THREE.MeshStandardMaterial
    Red: THREE.MeshStandardMaterial
  }
}

export default function PortfolioCardModel(props: Record<string, unknown>) {
  const { nodes, materials } = useGLTF(modelUrl) as unknown as GLTFResult

  // Fix/override materials at runtime (useful when GLB export colors don't match in-browser rendering)
  useMemo(() => {
    const lightYellow = materials['Light Yellow']
    if (lightYellow) {
      // Match the intended "paper" color more closely (tweak if needed)
      lightYellow.color = new THREE.Color('#E6E3CF')
      lightYellow.emissive = new THREE.Color('#000000')
      lightYellow.emissiveIntensity = 0
      lightYellow.roughness = 0.9
      lightYellow.metalness = 0.0
      lightYellow.needsUpdate = true
    }
  }, [materials])

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Card.geometry}
        material={materials['Light Yellow']}
        position={[0.908, 3.972, 0]}
        rotation={[-Math.PI, 0, 0]}
        scale={[-4.823, -6, -8.001]}
      />
      <mesh geometry={nodes.Jason_Poon.geometry} material={materials['Dark Blue']} position={[0.343, 4.072, 4.465]} rotation={[0, Math.PI / 2, 0]} scale={1.546} />
      <mesh geometry={nodes.Portfolio.geometry} material={materials['Dark Blue']} position={[1.872, 4.072, 2.087]} rotation={[0, Math.PI / 2, 0]} scale={0.974} />
      <mesh geometry={nodes['Tri-L1'].geometry} material={materials.Yellow} position={[-3.915, 3.972, 8.001]} scale={1.499} />
      <mesh geometry={nodes['Plane-L2'].geometry} material={materials.Red} position={[-3.898, 3.972, 5.979]} scale={[4.815, 0.999, 0.999]} />
      <mesh geometry={nodes['Plane-L1'].geometry} material={materials['Dark Blue']} position={[-3.898, 3.972, 5.979]} scale={[4.815, 0.999, 0.999]} />
      <mesh geometry={nodes['Circle-L1'].geometry} material={materials['Dark Blue']} position={[5.726, 3.972, 5.007]} scale={0.571} />
      <mesh geometry={nodes['Plane-R'].geometry} material={materials['Dark Blue']} position={[5.732, 4.105, -8.001]} scale={0.813} />
      <mesh geometry={nodes['Tri-R'].geometry} material={materials.Yellow} position={[3.293, 4.113, -8.001]} scale={0.813} />
      <mesh geometry={nodes['Tri-R002'].geometry} material={materials.Red} position={[4.919, 4.113, -4.75]} scale={0.813} />
      <mesh geometry={nodes['Tri-R003'].geometry} material={materials.Red} position={[4.919, 4.113, -3.125]} scale={0.813} />
      <mesh geometry={nodes['Tri-R004'].geometry} material={materials['Dark Blue']} position={[4.106, 4.113, -3.938]} rotation={[-Math.PI, 1.571, 0]} scale={0.813} />
      <mesh geometry={nodes['Plane-R-001'].geometry} material={materials['Dark Blue']} position={[3.293, 3.972, -5.563]} scale={0.813} />
      <mesh geometry={nodes['Tri-R005'].geometry} material={materials.Yellow} position={[4.919, 4.113, -6.376]} scale={0.813} />
      <mesh geometry={nodes['Tri-R-E001'].geometry} material={materials['Dark Blue']} position={[3.436, 3.972, -3.924]} rotation={[0, Math.PI / 2, 0]} scale={2.237} />
      <mesh geometry={nodes['Tri-R001'].geometry} material={materials.Red} position={[-3.102, 4.113, -3.938]} rotation={[0, 0, -Math.PI]} scale={0.813} />
      <mesh geometry={nodes['Tri-R006'].geometry} material={materials['Dark Blue']} position={[-3.915, 4.113, -5.563]} rotation={[-Math.PI, 1.571, 0]} scale={0.813} />
      <mesh geometry={nodes.Plane.geometry} material={materials.Yellow} position={[0.11, 3.972, -6.376]} scale={0.827} />
      <group position={[-2.664, 4.172, 5.954]} rotation={[0, -1.379, Math.PI]}>
        <mesh geometry={nodes.BézierCurve002.geometry} material={materials['Light Yellow']} />
        <mesh geometry={nodes.BézierCurve002_1.geometry} material={materials['Dark Blue']} />
        <mesh geometry={nodes.BézierCurve002_2.geometry} material={materials.Yellow} />
      </group>
      <mesh geometry={nodes.Star.geometry} material={materials['Dark Blue']} position={[-2.322, 3.972, -6.457]} />
      <mesh geometry={nodes.Plane001.geometry} material={materials['Dark Blue']} position={[5.732, 4.072, 6.047]} rotation={[0, 0, -Math.PI]} scale={[2.641, 0.11, 0.042]} />
    </group>
  )
}

useGLTF.preload(modelUrl)
