/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 src/animated/assets/Portfolio_v2.glb -t -o src/animated/models/PortfolioCardModel_v2.tsx 
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

import modelUrl from "../assets/Portfolio_v2.glb?url";

type GLTFResult = GLTF & {
  nodes: {
    Card: THREE.Mesh;
    ["Circle-L1"]: THREE.Mesh;
    BézierCurve002: THREE.Mesh;
    BézierCurve002_1: THREE.Mesh;
    BézierCurve002_2: THREE.Mesh;
    Jason_Poon: THREE.Mesh;
    Plane: THREE.Mesh;
    Plane001: THREE.Mesh;
    ["Plane-L1"]: THREE.Mesh;
    ["Plane-L2"]: THREE.Mesh;
    ["Plane-R"]: THREE.Mesh;
    ["Plane-R-001"]: THREE.Mesh;
    Portfolio: THREE.Mesh;
    Star: THREE.Mesh;
    ["Tri-L1"]: THREE.Mesh;
    ["Tri-R"]: THREE.Mesh;
    ["Tri-R001"]: THREE.Mesh;
    ["Tri-R002"]: THREE.Mesh;
    ["Tri-R003"]: THREE.Mesh;
    ["Tri-R004"]: THREE.Mesh;
    ["Tri-R005"]: THREE.Mesh;
    ["Tri-R006"]: THREE.Mesh;
    ["Tri-R-E001"]: THREE.Mesh;
    Circle007: THREE.Mesh;
    Circle008: THREE.Mesh;
    Circle020: THREE.Mesh;
    Circle020_1: THREE.Mesh;
    Circle010: THREE.Mesh;
    Plane010: THREE.Mesh;
    Plane011: THREE.Mesh;
    Plane012: THREE.Mesh;
    Plane013: THREE.Mesh;
    Plane014: THREE.Mesh;
    Circle005: THREE.Mesh;
    Plane002: THREE.Mesh;
    Plane003: THREE.Mesh;
    Plane004: THREE.Mesh;
    Plane005: THREE.Mesh;
    Plane006: THREE.Mesh;
    Plane007: THREE.Mesh;
    Plane008: THREE.Mesh;
    Plane034: THREE.Mesh;
    Plane034_1: THREE.Mesh;
    Text004: THREE.Mesh;
    Text002: THREE.Mesh;
    Plane046: THREE.Mesh;
    Plane046_1: THREE.Mesh;
    Plane046_2: THREE.Mesh;
    Plane032: THREE.Mesh;
    Plane032_1: THREE.Mesh;
    Text001: THREE.Mesh;
    Text005: THREE.Mesh;
    Plane030: THREE.Mesh;
    Plane030_1: THREE.Mesh;
    Circle: THREE.Mesh;
    Circle003: THREE.Mesh;
    Circle004: THREE.Mesh;
    Text: THREE.Mesh;
    Text003: THREE.Mesh;
    Plane035: THREE.Mesh;
    Plane035_1: THREE.Mesh;
    Plane033: THREE.Mesh;
    Plane033_1: THREE.Mesh;
    Plane036: THREE.Mesh;
    Plane036_1: THREE.Mesh;
  };
  materials: {
    ["Light Yellow"]: THREE.MeshStandardMaterial;
    ["Dark Blue"]: THREE.MeshStandardMaterial;
    Yellow: THREE.MeshStandardMaterial;
    Red: THREE.MeshStandardMaterial;
  };
};

export default function PortfolioCardModel(props: Record<string, unknown>) {
  const { nodes, materials } = useGLTF(modelUrl) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Card.geometry}
        material={materials["Light Yellow"]}
        position={[0.908, 3.972, 0]}
        rotation={[-Math.PI, 0, 0]}
        scale={[-4.823, -6, -8.001]}
      />
      <mesh
        geometry={nodes["Circle-L1"].geometry}
        material={materials["Dark Blue"]}
        position={[5.726, 3.972, 5.007]}
        scale={0.571}
      />
      <group position={[-2.664, 4.172, 5.954]} rotation={[0, -1.379, Math.PI]}>
        <mesh
          geometry={nodes.BézierCurve002.geometry}
          material={materials["Light Yellow"]}
        />
        <mesh
          geometry={nodes.BézierCurve002_1.geometry}
          material={materials["Dark Blue"]}
        />
        <mesh
          geometry={nodes.BézierCurve002_2.geometry}
          material={materials.Yellow}
        />
      </group>
      <mesh
        geometry={nodes.Jason_Poon.geometry}
        material={materials["Dark Blue"]}
        position={[0.343, 4.072, 4.465]}
        rotation={[0, Math.PI / 2, 0]}
        scale={1.546}
      />
      <mesh
        geometry={nodes.Plane.geometry}
        material={materials.Yellow}
        position={[0.11, 3.972, -6.376]}
        scale={0.827}
      />
      <mesh
        geometry={nodes.Plane001.geometry}
        material={materials["Dark Blue"]}
        position={[5.732, 4.072, 6.047]}
        rotation={[0, 0, -Math.PI]}
        scale={[2.641, 0.11, 0.042]}
      />
      <mesh
        geometry={nodes["Plane-L1"].geometry}
        material={materials["Dark Blue"]}
        position={[-3.898, 3.972, 5.979]}
        scale={[4.815, 0.999, 0.999]}
      />
      <mesh
        geometry={nodes["Plane-L2"].geometry}
        material={materials.Red}
        position={[-3.898, 3.972, 5.979]}
        scale={[4.815, 0.999, 0.999]}
      />
      <mesh
        geometry={nodes["Plane-R"].geometry}
        material={materials["Dark Blue"]}
        position={[5.732, 4.105, -8.001]}
        scale={0.813}
      />
      <mesh
        geometry={nodes["Plane-R-001"].geometry}
        material={materials["Dark Blue"]}
        position={[3.293, 3.972, -5.563]}
        scale={0.813}
      />
      <mesh
        geometry={nodes.Portfolio.geometry}
        material={materials["Dark Blue"]}
        position={[1.872, 4.072, 2.087]}
        rotation={[0, Math.PI / 2, 0]}
        scale={0.974}
      />
      <mesh
        geometry={nodes.Star.geometry}
        material={materials["Dark Blue"]}
        position={[-2.322, 3.972, -6.457]}
      />
      <mesh
        geometry={nodes["Tri-L1"].geometry}
        material={materials.Yellow}
        position={[-3.915, 3.972, 8.001]}
        scale={1.499}
      />
      <mesh
        geometry={nodes["Tri-R"].geometry}
        material={materials.Yellow}
        position={[3.293, 4.113, -8.001]}
        scale={0.813}
      />
      <mesh
        geometry={nodes["Tri-R001"].geometry}
        material={materials.Red}
        position={[-3.102, 4.113, -3.938]}
        rotation={[0, 0, -Math.PI]}
        scale={0.813}
      />
      <mesh
        geometry={nodes["Tri-R002"].geometry}
        material={materials.Red}
        position={[4.919, 4.113, -4.75]}
        scale={0.813}
      />
      <mesh
        geometry={nodes["Tri-R003"].geometry}
        material={materials.Red}
        position={[4.919, 4.113, -3.125]}
        scale={0.813}
      />
      <mesh
        geometry={nodes["Tri-R004"].geometry}
        material={materials["Dark Blue"]}
        position={[4.106, 4.113, -3.938]}
        rotation={[-Math.PI, 1.571, 0]}
        scale={0.813}
      />
      <mesh
        geometry={nodes["Tri-R005"].geometry}
        material={materials.Yellow}
        position={[4.919, 4.113, -6.376]}
        scale={0.813}
      />
      <mesh
        geometry={nodes["Tri-R006"].geometry}
        material={materials["Dark Blue"]}
        position={[-3.915, 4.113, -5.563]}
        rotation={[-Math.PI, 1.571, 0]}
        scale={0.813}
      />
      <mesh
        geometry={nodes["Tri-R-E001"].geometry}
        material={materials["Dark Blue"]}
        position={[3.436, 3.972, -3.924]}
        rotation={[0, Math.PI / 2, 0]}
        scale={2.237}
      />
      <mesh
        geometry={nodes.Circle007.geometry}
        material={materials.Yellow}
        position={[5.228, 3.847, -7.46]}
      />
      <mesh
        geometry={nodes.Circle008.geometry}
        material={materials["Dark Blue"]}
        position={[4.675, 3.847, -6.431]}
      />
      <group position={[5.709, 3.847, -4.631]}>
        <mesh geometry={nodes.Circle020.geometry} material={materials.Red} />
        <mesh
          geometry={nodes.Circle020_1.geometry}
          material={materials.Yellow}
        />
      </group>
      <mesh
        geometry={nodes.Circle010.geometry}
        material={materials["Dark Blue"]}
        position={[3.241, 3.847, -7.994]}
      />
      <mesh
        geometry={nodes.Plane010.geometry}
        material={materials.Red}
        position={[4.76, 3.847, 7.03]}
        scale={0.972}
      />
      <mesh
        geometry={nodes.Plane011.geometry}
        material={materials["Dark Blue"]}
        position={[2.817, 3.847, 7.03]}
        scale={0.972}
      />
      <mesh
        geometry={nodes.Plane012.geometry}
        material={materials.Yellow}
        position={[4.76, 3.847, 5.087]}
        scale={0.972}
      />
      <mesh
        geometry={nodes.Plane013.geometry}
        material={materials.Yellow}
        position={[3.219, 3.847, 6.627]}
        rotation={[-Math.PI, Math.PI / 4, -Math.PI]}
        scale={0.972}
      />
      <mesh
        geometry={nodes.Plane014.geometry}
        material={materials.Red}
        position={[5.732, 3.847, 4.115]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.972}
      />
      <mesh
        geometry={nodes.Circle005.geometry}
        material={materials.Red}
        position={[2.077, 3.691, -6.032]}
        scale={0.738}
      />
      <mesh
        geometry={nodes.Plane002.geometry}
        material={materials["Light Yellow"]}
        position={[1.841, 3.738, -6.312]}
        scale={0.588}
      />
      <mesh
        geometry={nodes.Plane003.geometry}
        material={materials["Dark Blue"]}
        position={[1.545, 3.691, -6.032]}
        scale={-0.225}
      />
      <mesh
        geometry={nodes.Plane004.geometry}
        material={materials["Dark Blue"]}
        position={[1.495, 3.691, -6.65]}
        scale={0.15}
      />
      <mesh
        geometry={nodes.Plane005.geometry}
        material={materials.Yellow}
        position={[1.944, 3.691, -6.65]}
        scale={0.15}
      />
      <mesh
        geometry={nodes.Plane006.geometry}
        material={materials.Yellow}
        position={[2.091, 3.691, -6.65]}
        scale={0.15}
      />
      <mesh
        geometry={nodes.Plane007.geometry}
        material={materials.Yellow}
        position={[2.224, 3.691, -6.65]}
        scale={0.15}
      />
      <mesh
        geometry={nodes.Plane008.geometry}
        material={materials.Yellow}
        position={[2.37, 3.691, -6.65]}
        scale={0.15}
      />
      <group position={[0.969, 3.841, -7.255]} scale={[1.975, 0.936, 2.352]}>
        <mesh
          geometry={nodes.Plane034.geometry}
          material={materials["Light Yellow"]}
        />
        <mesh
          geometry={nodes.Plane034_1.geometry}
          material={materials.Yellow}
        />
      </group>
      <mesh
        geometry={nodes.Text004.geometry}
        material={materials["Dark Blue"]}
        position={[3.189, 3.747, -7.056]}
        rotation={[Math.PI, Math.PI / 2, 0]}
        scale={0.52}
      />
      <mesh
        geometry={nodes.Text002.geometry}
        material={materials["Dark Blue"]}
        position={[2.119, 3.747, -5.46]}
        rotation={[Math.PI, Math.PI / 2, 0]}
        scale={1.208}
      />
      <group
        position={[-2.663, 3.691, 1.619]}
        rotation={[0, -0.275, 0]}
        scale={0.215}
      >
        <mesh geometry={nodes.Plane046.geometry} material={materials.Yellow} />
        <mesh
          geometry={nodes.Plane046_1.geometry}
          material={materials["Light Yellow"]}
        />
        <mesh
          geometry={nodes.Plane046_2.geometry}
          material={materials["Dark Blue"]}
        />
      </group>
      <group position={[-3.265, 3.841, -2.273]} scale={[1.975, 0.936, 2.352]}>
        <mesh
          geometry={nodes.Plane032.geometry}
          material={materials["Light Yellow"]}
        />
        <mesh geometry={nodes.Plane032_1.geometry} material={materials.Red} />
      </group>
      <mesh
        geometry={nodes.Text001.geometry}
        material={materials["Dark Blue"]}
        position={[-2.101, 3.747, -2.165]}
        rotation={[Math.PI, Math.PI / 2, 0]}
        scale={1.208}
      />
      <mesh
        geometry={nodes.Text005.geometry}
        material={materials["Dark Blue"]}
        position={[-0.947, 3.747, -2.061]}
        rotation={[Math.PI, Math.PI / 2, 0]}
        scale={0.52}
      />
      <group position={[-3.265, 3.841, -7.255]} scale={[1.975, 0.936, 2.352]}>
        <mesh
          geometry={nodes.Plane030.geometry}
          material={materials["Light Yellow"]}
        />
        <mesh
          geometry={nodes.Plane030_1.geometry}
          material={materials.Yellow}
        />
      </group>
      <mesh
        geometry={nodes.Circle.geometry}
        material={materials["Light Yellow"]}
        position={[-2.408, 3.738, -6.312]}
        scale={0.936}
      />
      <mesh
        geometry={nodes.Circle003.geometry}
        material={materials["Dark Blue"]}
        position={[-2.688, 3.691, -6.314]}
        scale={0.936}
      />
      <mesh
        geometry={nodes.Circle004.geometry}
        material={materials["Dark Blue"]}
        position={[-1.924, 3.691, -6.314]}
        scale={1.395}
      />
      <mesh
        geometry={nodes.Text.geometry}
        material={materials["Dark Blue"]}
        position={[-2.101, 3.747, -5.595]}
        rotation={[Math.PI, Math.PI / 2, 0]}
        scale={1.208}
      />
      <mesh
        geometry={nodes.Text003.geometry}
        material={materials["Dark Blue"]}
        position={[-0.891, 3.747, -7.056]}
        rotation={[Math.PI, Math.PI / 2, 0]}
        scale={0.52}
      />
      <group position={[0.969, 3.841, -2.273]} scale={[1.975, 0.936, 2.352]}>
        <mesh
          geometry={nodes.Plane035.geometry}
          material={materials["Light Yellow"]}
        />
        <mesh geometry={nodes.Plane035_1.geometry} material={materials.Red} />
      </group>
      <group position={[-3.265, 3.841, 2.71]} scale={[1.975, 0.936, 2.352]}>
        <mesh
          geometry={nodes.Plane033.geometry}
          material={materials["Light Yellow"]}
        />
        <mesh
          geometry={nodes.Plane033_1.geometry}
          material={materials["Dark Blue"]}
        />
      </group>
      <group position={[0.969, 3.841, 2.71]} scale={[1.975, 0.936, 2.352]}>
        <mesh
          geometry={nodes.Plane036.geometry}
          material={materials["Light Yellow"]}
        />
        <mesh
          geometry={nodes.Plane036_1.geometry}
          material={materials["Dark Blue"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/Portfolio_v2.glb");
