/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 src/animated/assets/Portfolio_v3.glb -t -o src/animated/models/PortfolioCardModel_v3.tsx 
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

import modelUrl from "../assets/Portfolio_v3.glb?url";

type GLTFResult = GLTF & {
  nodes: {
    Card: THREE.Mesh;
    Circle_FL_1: THREE.Mesh;
    BézierCurve002: THREE.Mesh;
    BézierCurve002_1: THREE.Mesh;
    BézierCurve002_2: THREE.Mesh;
    Title_F_1: THREE.Mesh;
    Plane_FR_1: THREE.Mesh;
    Cross_FL: THREE.Mesh;
    Plane_FL_1: THREE.Mesh;
    Plane_FL_2: THREE.Mesh;
    Plane_FR_2: THREE.Mesh;
    ["Plane-R-001"]: THREE.Mesh;
    Title_F_2: THREE.Mesh;
    Star_F: THREE.Mesh;
    Tri_FL_1: THREE.Mesh;
    Tri_FR_1: THREE.Mesh;
    Tri_FR_2: THREE.Mesh;
    Tri_FR_3: THREE.Mesh;
    Tri_FR_4: THREE.Mesh;
    Tri_FR_5: THREE.Mesh;
    Tri_FR_6: THREE.Mesh;
    Tri_FR_7: THREE.Mesh;
    Tri_FR_8: THREE.Mesh;
    Circle_BL_1: THREE.Mesh;
    Circle_BL_2: THREE.Mesh;
    Circle020: THREE.Mesh;
    Circle020_1: THREE.Mesh;
    Circle_BL_4: THREE.Mesh;
    Plane_BR_1: THREE.Mesh;
    Plane_BR_2: THREE.Mesh;
    Plane_BR_3: THREE.Mesh;
    Plane_BR_4: THREE.Mesh;
    Plane_BR_5: THREE.Mesh;
    Projects_Icon_1: THREE.Mesh;
    Projects_Icon_Background: THREE.Mesh;
    Projects_Icon_5: THREE.Mesh;
    Projects_Icon_6: THREE.Mesh;
    Projects_Icon_7: THREE.Mesh;
    Projects_Icon_4: THREE.Mesh;
    Projects_Icon_3: THREE.Mesh;
    Projects_Icon_2: THREE.Mesh;
    Plane034: THREE.Mesh;
    Plane034_1: THREE.Mesh;
    Projects_Info: THREE.Mesh;
    Projects_Header: THREE.Mesh;
    Plane046: THREE.Mesh;
    Plane046_1: THREE.Mesh;
    Plane046_2: THREE.Mesh;
    Plane032: THREE.Mesh;
    Plane032_1: THREE.Mesh;
    Community_Header: THREE.Mesh;
    Community_Info: THREE.Mesh;
    Plane030: THREE.Mesh;
    Plane030_1: THREE.Mesh;
    AboutMe_Icon_Background: THREE.Mesh;
    AboutMe_Icon_Avatar_1: THREE.Mesh;
    AboutMe_Icon_Avatar_2: THREE.Mesh;
    AboutMe_Header: THREE.Mesh;
    AboutMe_Info: THREE.Mesh;
    Plane035: THREE.Mesh;
    Plane035_1: THREE.Mesh;
    Plane059: THREE.Mesh;
    Plane059_1: THREE.Mesh;
    Working_Icon_1: THREE.Mesh;
    Working_Icon_2: THREE.Mesh;
    Working_Icon_3: THREE.Mesh;
    Working_Icon_4: THREE.Mesh;
    Working_Icon_6: THREE.Mesh;
    Working_Icon_8: THREE.Mesh;
    Working_Icon_5: THREE.Mesh;
    Working_Icon_7: THREE.Mesh;
    Working_Icon_9: THREE.Mesh;
    Circle022: THREE.Mesh;
    Circle022_1: THREE.Mesh;
    Working_Header: THREE.Mesh;
    Working_Info: THREE.Mesh;
    Plane033: THREE.Mesh;
    Plane033_1: THREE.Mesh;
    Circle001: THREE.Mesh;
    Circle001_1: THREE.Mesh;
    Circle001_2: THREE.Mesh;
    Awards_Info: THREE.Mesh;
    Awards_Header: THREE.Mesh;
    Plane036: THREE.Mesh;
    Plane036_1: THREE.Mesh;
    Education_Header: THREE.Mesh;
    Education_Info: THREE.Mesh;
    Plane007: THREE.Mesh;
    Plane007_1: THREE.Mesh;
    Plane007_2: THREE.Mesh;
  };
  materials: {
    ["Light Yellow"]: THREE.MeshStandardMaterial;
    ["Dark Blue"]: THREE.MeshStandardMaterial;
    Yellow: THREE.MeshStandardMaterial;
    Red: THREE.MeshStandardMaterial;
  };
};

export default function PortfolioCardModel(props: Record<string, unknown>) {
  const { nodes, materials } = useGLTF(modelUrl) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Card.geometry}
        material={materials["Light Yellow"]}
        position={[0.908, 3.972, 0]}
        rotation={[-Math.PI, 0, 0]}
        scale={[-4.823, -6, -8.001]}
      />
      <mesh
        geometry={nodes.Circle_FL_1.geometry}
        material={materials["Dark Blue"]}
        position={[5.726, 3.972, 5.007]}
        scale={0.571}
      />
      <group position={[-2.664, 4.172, 5.954]} rotation={[0, -1.379, Math.PI]}>
        <mesh
          geometry={nodes.BézierCurve002.geometry}
          material={materials["Light Yellow"]}
        />
        <mesh
          geometry={nodes.BézierCurve002_1.geometry}
          material={materials["Dark Blue"]}
        />
        <mesh
          geometry={nodes.BézierCurve002_2.geometry}
          material={materials.Yellow}
        />
      </group>
      <mesh
        geometry={nodes.Title_F_1.geometry}
        material={materials["Dark Blue"]}
        position={[0.343, 4.072, 4.465]}
        rotation={[0, Math.PI / 2, 0]}
        scale={1.546}
      />
      <mesh
        geometry={nodes.Plane_FR_1.geometry}
        material={materials.Yellow}
        position={[0.11, 3.972, -6.376]}
        scale={0.827}
      />
      <mesh
        geometry={nodes.Cross_FL.geometry}
        material={materials["Dark Blue"]}
        position={[5.732, 4.072, 6.047]}
        rotation={[0, 0, -Math.PI]}
        scale={[2.641, 0.11, 0.042]}
      />
      <mesh
        geometry={nodes.Plane_FL_1.geometry}
        material={materials["Dark Blue"]}
        position={[-3.898, 3.972, 5.979]}
        scale={[4.815, 0.999, 0.999]}
      />
      <mesh
        geometry={nodes.Plane_FL_2.geometry}
        material={materials.Red}
        position={[-3.898, 3.972, 5.979]}
        scale={[4.815, 0.999, 0.999]}
      />
      <mesh
        geometry={nodes.Plane_FR_2.geometry}
        material={materials["Dark Blue"]}
        position={[5.732, 4.105, -8.001]}
        scale={0.813}
      />
      <mesh
        geometry={nodes["Plane-R-001"].geometry}
        material={materials["Dark Blue"]}
        position={[3.293, 3.972, -5.563]}
        scale={0.813}
      />
      <mesh
        geometry={nodes.Title_F_2.geometry}
        material={materials["Dark Blue"]}
        position={[1.872, 4.072, 2.087]}
        rotation={[0, Math.PI / 2, 0]}
        scale={0.974}
      />
      <mesh
        geometry={nodes.Star_F.geometry}
        material={materials["Dark Blue"]}
        position={[-2.322, 3.972, -6.457]}
      />
      <mesh
        geometry={nodes.Tri_FL_1.geometry}
        material={materials.Yellow}
        position={[-3.915, 3.972, 8.001]}
        scale={1.499}
      />
      <mesh
        geometry={nodes.Tri_FR_1.geometry}
        material={materials.Yellow}
        position={[3.293, 4.113, -8.001]}
        scale={0.813}
      />
      <mesh
        geometry={nodes.Tri_FR_2.geometry}
        material={materials.Red}
        position={[-3.102, 4.113, -3.938]}
        rotation={[0, 0, -Math.PI]}
        scale={0.813}
      />
      <mesh
        geometry={nodes.Tri_FR_3.geometry}
        material={materials.Red}
        position={[4.919, 4.113, -4.75]}
        scale={0.813}
      />
      <mesh
        geometry={nodes.Tri_FR_4.geometry}
        material={materials.Red}
        position={[4.919, 4.113, -3.125]}
        scale={0.813}
      />
      <mesh
        geometry={nodes.Tri_FR_5.geometry}
        material={materials["Dark Blue"]}
        position={[4.106, 4.113, -3.938]}
        rotation={[-Math.PI, 1.571, 0]}
        scale={0.813}
      />
      <mesh
        geometry={nodes.Tri_FR_6.geometry}
        material={materials.Yellow}
        position={[4.919, 4.113, -6.376]}
        scale={0.813}
      />
      <mesh
        geometry={nodes.Tri_FR_7.geometry}
        material={materials["Dark Blue"]}
        position={[-3.915, 4.113, -5.563]}
        rotation={[-Math.PI, 1.571, 0]}
        scale={0.813}
      />
      <mesh
        geometry={nodes.Tri_FR_8.geometry}
        material={materials["Dark Blue"]}
        position={[3.436, 3.972, -3.924]}
        rotation={[0, Math.PI / 2, 0]}
        scale={2.237}
      />
      <mesh
        geometry={nodes.Circle_BL_1.geometry}
        material={materials.Yellow}
        position={[5.228, 3.847, -7.46]}
      />
      <mesh
        geometry={nodes.Circle_BL_2.geometry}
        material={materials["Dark Blue"]}
        position={[4.675, 3.847, -6.431]}
      />
      <group position={[5.709, 3.847, -4.631]}>
        <mesh geometry={nodes.Circle020.geometry} material={materials.Red} />
        <mesh
          geometry={nodes.Circle020_1.geometry}
          material={materials.Yellow}
        />
      </group>
      <mesh
        geometry={nodes.Circle_BL_4.geometry}
        material={materials["Dark Blue"]}
        position={[3.241, 3.847, -7.994]}
      />
      <mesh
        geometry={nodes.Plane_BR_1.geometry}
        material={materials.Red}
        position={[4.76, 3.847, 7.03]}
        scale={0.972}
      />
      <mesh
        geometry={nodes.Plane_BR_2.geometry}
        material={materials["Dark Blue"]}
        position={[2.817, 3.847, 7.03]}
        scale={0.972}
      />
      <mesh
        geometry={nodes.Plane_BR_3.geometry}
        material={materials.Yellow}
        position={[4.76, 3.847, 5.087]}
        scale={0.972}
      />
      <mesh
        geometry={nodes.Plane_BR_4.geometry}
        material={materials.Yellow}
        position={[3.219, 3.847, 6.627]}
        rotation={[-Math.PI, Math.PI / 4, -Math.PI]}
        scale={0.972}
      />
      <mesh
        geometry={nodes.Plane_BR_5.geometry}
        material={materials.Red}
        position={[5.732, 3.847, 4.115]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.972}
      />
      <mesh
        geometry={nodes.Projects_Icon_1.geometry}
        material={materials.Red}
        position={[2.077, 3.691, -6.032]}
        scale={0.738}
      />
      <mesh
        geometry={nodes.Projects_Icon_Background.geometry}
        material={materials["Light Yellow"]}
        position={[1.841, 3.738, -6.312]}
        scale={0.588}
      />
      <mesh
        geometry={nodes.Projects_Icon_5.geometry}
        material={materials["Dark Blue"]}
        position={[1.545, 3.691, -6.032]}
        scale={-0.225}
      />
      <mesh
        geometry={nodes.Projects_Icon_6.geometry}
        material={materials["Dark Blue"]}
        position={[1.495, 3.691, -6.65]}
        scale={0.15}
      />
      <mesh
        geometry={nodes.Projects_Icon_7.geometry}
        material={materials.Yellow}
        position={[1.944, 3.691, -6.65]}
        scale={0.15}
      />
      <mesh
        geometry={nodes.Projects_Icon_4.geometry}
        material={materials.Yellow}
        position={[2.091, 3.691, -6.65]}
        scale={0.15}
      />
      <mesh
        geometry={nodes.Projects_Icon_3.geometry}
        material={materials.Yellow}
        position={[2.224, 3.691, -6.65]}
        scale={0.15}
      />
      <mesh
        geometry={nodes.Projects_Icon_2.geometry}
        material={materials.Yellow}
        position={[2.37, 3.691, -6.65]}
        scale={0.15}
      />
      <group position={[0.969, 3.841, -7.255]} scale={[1.975, 0.936, 2.352]}>
        <mesh
          geometry={nodes.Plane034.geometry}
          material={materials["Light Yellow"]}
        />
        <mesh
          geometry={nodes.Plane034_1.geometry}
          material={materials.Yellow}
        />
      </group>
      <mesh
        geometry={nodes.Projects_Info.geometry}
        material={materials["Dark Blue"]}
        position={[3.189, 3.747, -7.056]}
        rotation={[Math.PI, Math.PI / 2, 0]}
        scale={0.52}
      />
      <mesh
        geometry={nodes.Projects_Header.geometry}
        material={materials["Dark Blue"]}
        position={[2.119, 3.747, -5.46]}
        rotation={[Math.PI, Math.PI / 2, 0]}
        scale={1.208}
      />
      <group
        position={[-2.663, 3.691, 1.619]}
        rotation={[0, -0.275, 0]}
        scale={0.215}
      >
        <mesh geometry={nodes.Plane046.geometry} material={materials.Yellow} />
        <mesh
          geometry={nodes.Plane046_1.geometry}
          material={materials["Light Yellow"]}
        />
        <mesh
          geometry={nodes.Plane046_2.geometry}
          material={materials["Dark Blue"]}
        />
      </group>
      <group position={[-3.265, 3.841, -2.273]} scale={[1.975, 0.936, 2.352]}>
        <mesh
          geometry={nodes.Plane032.geometry}
          material={materials["Light Yellow"]}
        />
        <mesh geometry={nodes.Plane032_1.geometry} material={materials.Red} />
      </group>
      <mesh
        geometry={nodes.Community_Header.geometry}
        material={materials["Dark Blue"]}
        position={[-2.101, 3.747, -2.165]}
        rotation={[Math.PI, Math.PI / 2, 0]}
        scale={1.208}
      />
      <mesh
        geometry={nodes.Community_Info.geometry}
        material={materials["Dark Blue"]}
        position={[-0.947, 3.747, -2.061]}
        rotation={[Math.PI, Math.PI / 2, 0]}
        scale={0.52}
      />
      <group position={[-3.265, 3.841, -7.255]} scale={[1.975, 0.936, 2.352]}>
        <mesh
          geometry={nodes.Plane030.geometry}
          material={materials["Light Yellow"]}
        />
        <mesh
          geometry={nodes.Plane030_1.geometry}
          material={materials.Yellow}
        />
      </group>
      <mesh
        geometry={nodes.AboutMe_Icon_Background.geometry}
        material={materials["Light Yellow"]}
        position={[-2.408, 3.738, -6.312]}
        scale={0.936}
      />
      <mesh
        geometry={nodes.AboutMe_Icon_Avatar_1.geometry}
        material={materials["Dark Blue"]}
        position={[-2.688, 3.691, -6.314]}
        scale={0.936}
      />
      <mesh
        geometry={nodes.AboutMe_Icon_Avatar_2.geometry}
        material={materials["Dark Blue"]}
        position={[-1.924, 3.691, -6.314]}
        scale={1.395}
      />
      <mesh
        geometry={nodes.AboutMe_Header.geometry}
        material={materials["Dark Blue"]}
        position={[-2.101, 3.747, -5.595]}
        rotation={[Math.PI, Math.PI / 2, 0]}
        scale={1.208}
      />
      <mesh
        geometry={nodes.AboutMe_Info.geometry}
        material={materials["Dark Blue"]}
        position={[-0.891, 3.747, -7.056]}
        rotation={[Math.PI, Math.PI / 2, 0]}
        scale={0.52}
      />
      <group position={[0.969, 3.841, -2.273]} scale={[1.975, 0.936, 2.352]}>
        <mesh
          geometry={nodes.Plane035.geometry}
          material={materials["Light Yellow"]}
        />
        <mesh geometry={nodes.Plane035_1.geometry} material={materials.Red} />
      </group>
      <group position={[1.629, 3.747, 1.051]} scale={[0.452, 0.452, 0.581]}>
        <mesh
          geometry={nodes.Plane059.geometry}
          material={materials["Dark Blue"]}
        />
        <mesh
          geometry={nodes.Plane059_1.geometry}
          material={materials["Light Yellow"]}
        />
      </group>
      <mesh
        geometry={nodes.Working_Icon_1.geometry}
        material={materials.Red}
        position={[1.426, 3.737, 0.806]}
        scale={[0.038, 0.038, 0.171]}
      />
      <mesh
        geometry={nodes.Working_Icon_2.geometry}
        material={materials["Dark Blue"]}
        position={[1.679, 3.747, 0.764]}
        rotation={[0, Math.PI / 4, 0]}
        scale={-0.092}
      />
      <mesh
        geometry={nodes.Working_Icon_3.geometry}
        material={materials.Yellow}
        position={[1.584, 3.737, 1.199]}
        scale={[0.014, 0.03, 0.251]}
      />
      <mesh
        geometry={nodes.Working_Icon_4.geometry}
        material={materials.Yellow}
        position={[1.649, 3.737, 1.054]}
        scale={[0.014, 0.03, 0.107]}
      />
      <mesh
        geometry={nodes.Working_Icon_6.geometry}
        material={materials.Yellow}
        position={[1.706, 3.737, 1.054]}
        scale={[0.014, 0.03, 0.107]}
      />
      <mesh
        geometry={nodes.Working_Icon_8.geometry}
        material={materials.Yellow}
        position={[1.767, 3.737, 1.054]}
        scale={[0.014, 0.03, 0.107]}
      />
      <mesh
        geometry={nodes.Working_Icon_5.geometry}
        material={materials.Yellow}
        position={[1.649, 3.737, 1.342]}
        scale={[0.014, 0.03, 0.107]}
      />
      <mesh
        geometry={nodes.Working_Icon_7.geometry}
        material={materials.Yellow}
        position={[1.706, 3.737, 1.342]}
        scale={[0.014, 0.03, 0.107]}
      />
      <mesh
        geometry={nodes.Working_Icon_9.geometry}
        material={materials.Yellow}
        position={[1.767, 3.737, 1.342]}
        scale={[0.014, 0.03, 0.107]}
      />
      <group position={[1.891, 3.747, 1.788]}>
        <mesh geometry={nodes.Circle022.geometry} material={materials.Yellow} />
        <mesh
          geometry={nodes.Circle022_1.geometry}
          material={materials["Light Yellow"]}
        />
      </group>
      <mesh
        geometry={nodes.Working_Header.geometry}
        material={materials["Dark Blue"]}
        position={[2.103, 3.747, -1.996]}
        rotation={[-Math.PI, Math.PI / 2, 0]}
        scale={1.09}
      />
      <mesh
        geometry={nodes.Working_Info.geometry}
        material={materials["Dark Blue"]}
        position={[3.207, 3.747, -2.131]}
        rotation={[Math.PI, Math.PI / 2, 0]}
        scale={0.435}
      />
      <group position={[-3.263, 3.842, 2.712]} scale={[1.975, 0.936, 2.352]}>
        <mesh
          geometry={nodes.Plane033.geometry}
          material={materials["Light Yellow"]}
        />
        <mesh
          geometry={nodes.Plane033_1.geometry}
          material={materials["Dark Blue"]}
        />
      </group>
      <group
        position={[-2.613, 3.697, 6.503]}
        rotation={[0, -0.321, 0]}
        scale={1.498}
      >
        <mesh geometry={nodes.Circle001.geometry} material={materials.Red} />
        <mesh
          geometry={nodes.Circle001_1.geometry}
          material={materials.Yellow}
        />
        <mesh
          geometry={nodes.Circle001_2.geometry}
          material={materials["Light Yellow"]}
        />
      </group>
      <mesh
        geometry={nodes.Awards_Info.geometry}
        material={materials["Dark Blue"]}
        position={[-1.002, 3.747, 2.994]}
        rotation={[Math.PI, Math.PI / 2, 0]}
        scale={0.538}
      />
      <mesh
        geometry={nodes.Awards_Header.geometry}
        material={materials["Light Yellow"]}
        position={[-2.069, 3.747, 3.169]}
        rotation={[Math.PI, Math.PI / 2, 0]}
        scale={1.385}
      />
      <group position={[0.969, 3.841, 2.71]} scale={[1.975, 0.936, 2.352]}>
        <mesh
          geometry={nodes.Plane036.geometry}
          material={materials["Light Yellow"]}
        />
        <mesh
          geometry={nodes.Plane036_1.geometry}
          material={materials["Dark Blue"]}
        />
      </group>
      <mesh
        geometry={nodes.Education_Header.geometry}
        material={materials["Light Yellow"]}
        position={[2.138, 3.747, 2.89]}
        rotation={[Math.PI, Math.PI / 2, 0]}
        scale={1.314}
      />
      <mesh
        geometry={nodes.Education_Info.geometry}
        material={materials["Dark Blue"]}
        position={[3.192, 3.747, 2.904]}
        rotation={[Math.PI, Math.PI / 2, 0]}
        scale={0.458}
      />
      <group position={[1.652, 3.747, 7.058]} scale={-0.04}>
        <mesh geometry={nodes.Plane007.geometry} material={materials.Red} />
        <mesh
          geometry={nodes.Plane007_1.geometry}
          material={materials.Yellow}
        />
        <mesh
          geometry={nodes.Plane007_2.geometry}
          material={materials["Light Yellow"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/Portfolio_v3.glb");
