/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 src/animated/assets/camera-model.glb -t -o src/animated/components/model/Camera.tsx 
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

import modelUrl from "../../assets/camera-model.glb?url";

type GLTFResult = GLTF & {
  nodes: {
    model: THREE.Mesh;
  };
  materials: {
    model: THREE.MeshStandardMaterial;
  };
};

export function Camera(props: React.JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(modelUrl) as unknown as GLTFResult;

  // Apply vectorized material settings to match card aesthetic
  const cameraBaseMaterial = materials.model;
  if (cameraBaseMaterial instanceof THREE.MeshStandardMaterial) {
    cameraBaseMaterial.roughness = 0.75; // Higher roughness for matte appearance
    cameraBaseMaterial.metalness = 0.5; // Lower metalness for less reflective look
    cameraBaseMaterial.envMapIntensity = 0.3; // Reduce environment reflection
  }

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.model.geometry}
        material={materials.model}
        castShadow
      />
    </group>
  );
}

useGLTF.preload(modelUrl);
