/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 src/animated/assets/stylized_cartoon_shoes.glb -t -o src/animated/components/model/CartoonShoesModel.tsx 
Author: Ndevisuals (https://sketchfab.com/Wade23)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/stylized-cartoon-shoes-9b2062f2b9b24ac48af747f4bb397478
Title: Stylized Cartoon Shoes
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

import modelUrl from '../../assets/stylized_cartoon_shoes.glb?url'

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh
    Object_5: THREE.Mesh
    Object_6: THREE.Mesh
    Object_8: THREE.Mesh
    Object_9: THREE.Mesh
    Object_10: THREE.Mesh
  }
  materials: {
    White: THREE.MeshStandardMaterial
    Blue_Jeans: THREE.MeshStandardMaterial
    Metalic: THREE.MeshStandardMaterial
  }
}

export function CartoonShoesModel(props: React.JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(modelUrl) as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0, 2.565, 0.001]} rotation={[0.702, 0, 0]}>
        <mesh geometry={nodes.Object_4.geometry} material={materials.White} castShadow />
        <mesh geometry={nodes.Object_5.geometry} material={materials.Blue_Jeans} castShadow />
        <mesh geometry={nodes.Object_6.geometry} material={materials.Metalic} castShadow />
      </group>
      <group position={[-2.243, 0.812, -0.316]} rotation={[0, -0.284, 0]} scale={[-1, 1, 1]}>
        <mesh geometry={nodes.Object_8.geometry} material={materials.White} castShadow />
        <mesh geometry={nodes.Object_9.geometry} material={materials.Blue_Jeans} castShadow />
        <mesh geometry={nodes.Object_10.geometry} material={materials.Metalic} castShadow />
      </group>
    </group>
  )
}

useGLTF.preload(modelUrl)

