/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Fixed to use scene-level rendering to avoid node name mismatches.

Author: Spherveli (https://sketchfab.com/spherveli0)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pom-pom-7e50fbcb1b3e4f00974e8d95bc70eb07
Title: Pom-Pom
*/

import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import { useMemo, useRef } from 'react'
import * as THREE from 'three'
import { useSectionSelectionStore } from '../../../shared/stores'

import modelUrl from '../../assets/pom-pom.glb?url'

export function PomPomModel(props: React.JSX.IntrinsicElements['group']) {
  const { scene } = useGLTF(modelUrl)
  const groupRef = useRef<THREE.Group>(null)
  const timeRef = useRef(0)
  const isFocused = useSectionSelectionStore((state) => state.isFocused)

  const clonedScene = useMemo(() => {
    const clone = scene.clone(true)
    clone.traverse((child) => {
      if (child instanceof THREE.Mesh) {
        child.castShadow = true
        child.receiveShadow = true
      }
    })
    return clone
  }, [scene])

  useFrame((_, delta) => {
    if (!groupRef.current || isFocused) return
    timeRef.current += delta
    // Gentle left-right rocking — oscillates ±0.12 radians (~7°) at a slow pace
    groupRef.current.rotation.z = Math.sin(timeRef.current * 1.2) * 0.12
  })

  return (
    <group ref={groupRef} {...props} dispose={null}>
      <primitive object={clonedScene} />
    </group>
  )
}

useGLTF.preload(modelUrl)
