/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 src/animated/assets/Portfolio_v4.glb -t -o src/animated/components/model/PortfolioCardModel.tsx
*/

import { useGLTF } from "@react-three/drei";
import { useLayoutEffect, useMemo, useRef } from "react";
import * as THREE from "three";

import modelUrl from "../../assets/Portfolio_v4.glb?url";
import { BackAboutMe } from "./BackAboutMe";
import { BackAwards } from "./BackAwards";
import { BackCommunity } from "./BackCommunity";
import { BackEducation } from "./BackEducation";
import { BackFaceBase } from "./BackFaceBase";
import { BackProjects } from "./BackProjects";
import { BackWorking } from "./BackWorking";
import { FrontFace } from "./FrontFace";
import type { GLTFResult } from "./types";
import { useSectionSelectionStore } from "../../../shared/stores";

export default function PortfolioCardModel({
  ...props
}: Record<string, unknown>) {
  const { nodes, materials } = useGLTF(modelUrl) as unknown as GLTFResult;
  const cardPosition: [number, number, number] = [-0.107, 9.156, -1.2];
  const cardCenter = useMemo(() => {
    const geometry = nodes.Card.geometry;
    geometry.computeBoundingBox();

    const center = new THREE.Vector3();
    geometry.boundingBox?.getCenter(center);
    return center;
  }, [nodes]);

  const cardCenterOffset = useMemo<[number, number, number]>(() => {
    const offset = new THREE.Vector3().fromArray(cardPosition).add(cardCenter);
    return [-offset.x, -offset.y, -offset.z];
  }, [cardCenter]);
  const modelRef = useRef<THREE.Group | null>(null);
  const setSelectedSection = useSectionSelectionStore(
    (state) => state.setSelectedSection,
  );

  useLayoutEffect(() => {
    const lightYellow = materials["Light Yellow"];
    if (lightYellow) {
      lightYellow.color = new THREE.Color("#FFFFFF");
      lightYellow.needsUpdate = true;
    }

    // Make all materials double-sided so card is visible from all angles
    Object.values(materials).forEach((material) => {
      if (material instanceof THREE.Material) {
        material.side = THREE.DoubleSide;
        material.needsUpdate = true;
      }
    });
  }, [materials]);

  return (
    <group {...props} dispose={null}>
      <group ref={modelRef} position={cardCenterOffset}>
        <FrontFace
          nodes={nodes}
          materials={materials}
          cardPosition={cardPosition}
        />
        <BackFaceBase nodes={nodes} materials={materials} />
        <BackProjects
          nodes={nodes}
          materials={materials}
          onSelect={(position) =>
            setSelectedSection({ id: "projects", target: position })
          }
        />
        <BackCommunity
          nodes={nodes}
          materials={materials}
          onSelect={(position) =>
            setSelectedSection({ id: "community", target: position })
          }
        />
        <BackAboutMe
          nodes={nodes}
          materials={materials}
          onSelect={(position) =>
            setSelectedSection({ id: "aboutMe", target: position })
          }
        />
        <BackWorking
          nodes={nodes}
          materials={materials}
          onSelect={(position) =>
            setSelectedSection({ id: "working", target: position })
          }
        />
        <BackAwards
          nodes={nodes}
          materials={materials}
          onSelect={(position) =>
            setSelectedSection({ id: "awards", target: position })
          }
        />
        <BackEducation
          nodes={nodes}
          materials={materials}
          onSelect={(position) =>
            setSelectedSection({ id: "education", target: position })
          }
        />
      </group>
    </group>
  );
}

useGLTF.preload(modelUrl);
