/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 src/animated/assets/Portfolio_v3.glb -t -o src/animated/models/PortfolioCardModel_v3.tsx
*/

import { useGLTF } from "@react-three/drei";
import { useLayoutEffect, useRef } from "react";
import * as THREE from "three";

import modelUrl from "../../assets/Portfolio_v3.glb?url";
import { BackAboutMe } from "./BackAboutMe";
import { BackAwards } from "./BackAwards";
import { BackCommunity } from "./BackCommunity";
import { BackEducation } from "./BackEducation";
import { BackFaceBase } from "./BackFaceBase";
import { BackProjects } from "./BackProjects";
import { BackWorking } from "./BackWorking";
import { FrontFace } from "./FrontFace";
import type { GLTFResult } from "./types";
import { useSectionSelectionStore } from "../../../shared/stores";
import { useCameraPoseStore } from "../../../shared/stores";
import { isCameraBehindCard } from "../../utils/focusGuard";

export default function PortfolioCardModel({
  ...props
}: Record<string, unknown>) {
  const { nodes, materials } = useGLTF(modelUrl) as unknown as GLTFResult;
  const modelRef = useRef<THREE.Group | null>(null);
  const setSelectedSection = useSectionSelectionStore(
    (state) => state.setSelectedSection,
  );
  const cameraPoseStore = useCameraPoseStore;

  const canFocusFromCamera = () => {
    const { cameraPosition, hasCameraPose } = cameraPoseStore.getState();
    if (!hasCameraPose) return false;
    return isCameraBehindCard(cameraPosition);
  };

  useLayoutEffect(() => {
    const lightYellow = materials["Light Yellow"];
    if (lightYellow) {
      lightYellow.color = new THREE.Color("#FFFFFF");
      lightYellow.needsUpdate = true;
    }
  }, [materials]);

  useLayoutEffect(() => {
    const group = modelRef.current;
    if (!group) return;

    const box = new THREE.Box3().setFromObject(group);
    if (box.isEmpty()) return;

    const center = new THREE.Vector3();
    box.getCenter(center);
    group.position.set(-center.x, -center.y, -center.z);
  }, []);

  return (
    <group {...props} dispose={null}>
      <group ref={modelRef}>
        <FrontFace nodes={nodes} materials={materials} />
        <BackFaceBase nodes={nodes} materials={materials} />
        <BackProjects
          nodes={nodes}
          materials={materials}
          onSelect={(position) =>
            canFocusFromCamera() &&
            setSelectedSection({ id: "projects", target: position })
          }
        />
        <BackCommunity
          nodes={nodes}
          materials={materials}
          onSelect={(position) =>
            canFocusFromCamera() &&
            setSelectedSection({ id: "community", target: position })
          }
        />
        <BackAboutMe
          nodes={nodes}
          materials={materials}
          onSelect={(position) =>
            canFocusFromCamera() &&
            setSelectedSection({ id: "aboutMe", target: position })
          }
        />
        <BackWorking
          nodes={nodes}
          materials={materials}
          onSelect={(position) =>
            canFocusFromCamera() &&
            setSelectedSection({ id: "working", target: position })
          }
        />
        <BackAwards
          nodes={nodes}
          materials={materials}
          onSelect={(position) =>
            canFocusFromCamera() &&
            setSelectedSection({ id: "awards", target: position })
          }
        />
        <BackEducation
          nodes={nodes}
          materials={materials}
          onSelect={(position) =>
            canFocusFromCamera() &&
            setSelectedSection({ id: "education", target: position })
          }
        />
      </group>
    </group>
  );
}

useGLTF.preload(modelUrl);
