/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 src/animated/assets/shoes-model.glb -t -o src/animated/components/model/Shoes.tsx 
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import modelUrl from "../../assets/shoes-model.glb?url";

type GLTFResult = GLTF & {
  nodes: {
    model: THREE.Mesh;
  };
  materials: {
    model: THREE.MeshStandardMaterial;
  };
};

export function Shoes(props: React.JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(modelUrl) as unknown as GLTFResult;

  // Apply vectorized material settings to match card aesthetic
  const shoesBaseMaterial = materials.model;
  if (shoesBaseMaterial instanceof THREE.MeshStandardMaterial) {
    shoesBaseMaterial.roughness = 0.75; // Higher roughness for matte appearance
    shoesBaseMaterial.metalness = 0.5; // Lower metalness for less reflective look
    shoesBaseMaterial.envMapIntensity = 0.3; // Reduce environment reflection
  }

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.model.geometry}
        material={materials.model}
        castShadow
      />
    </group>
  );
}

useGLTF.preload(modelUrl);
