/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 src/animated/assets/simple_camera_model.glb -t -o src/animated/components/model/SimpleCameraModel.tsx 
Author: Diodio80 (https://sketchfab.com/DiogoCosta23)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/simple-camera-model-cf52730a70764a828c29c9680f6e283e
Title: Simple Camera Model
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

import modelUrl from '../../assets/simple_camera_model.glb?url'

type GLTFResult = GLTF & {
  nodes: {
    Object_6: THREE.Mesh
    Object_8: THREE.Mesh
    Object_10: THREE.Mesh
    Object_12: THREE.Mesh
    Object_14: THREE.Mesh
    Object_16: THREE.Mesh
    Object_18: THREE.Mesh
    Object_20: THREE.Mesh
    Object_22: THREE.Mesh
    Object_24: THREE.Mesh
    Object_26: THREE.Mesh
    Object_28: THREE.Mesh
    Object_30: THREE.Mesh
    Object_32: THREE.Mesh
    Object_34: THREE.Mesh
    Object_37: THREE.Mesh
    Object_39: THREE.Mesh
    Object_41: THREE.Mesh
    Object_43: THREE.Mesh
    Object_45: THREE.Mesh
  }
  materials: {
    material_0: THREE.MeshStandardMaterial
  }
}

export function SimpleCameraModel(props: React.JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(modelUrl) as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_6.geometry} material={materials.material_0} position={[0, 0, -0.031]} castShadow />
      <mesh geometry={nodes.Object_8.geometry} material={materials.material_0} position={[0, 0, -0.063]} castShadow />
      <mesh geometry={nodes.Object_10.geometry} material={materials.material_0} position={[0, 0, -0.063]} castShadow />
      <mesh geometry={nodes.Object_12.geometry} material={materials.material_0} position={[0, 0, -0.063]} castShadow />
      <mesh geometry={nodes.Object_14.geometry} material={materials.material_0} position={[0, 0, -0.063]} castShadow />
      <mesh geometry={nodes.Object_16.geometry} material={materials.material_0} position={[0, 0, -0.063]} castShadow />
      <mesh geometry={nodes.Object_18.geometry} material={materials.material_0} position={[-0.125, 0.438, -0.125]} castShadow />
      <mesh geometry={nodes.Object_20.geometry} material={materials.material_0} position={[-0.125, 0.469, -0.162]} rotation={[0.593, 0, 0]} castShadow />
      <mesh geometry={nodes.Object_22.geometry} material={materials.material_0} position={[-0.125, 0.438, -0.131]} castShadow />
      <mesh geometry={nodes.Object_24.geometry} material={materials.material_0} position={[-0.125, 0.381, -0.131]} castShadow />
      <mesh geometry={nodes.Object_26.geometry} material={materials.material_0} position={[-0.125, 0.387, -0.131]} castShadow />
      <mesh geometry={nodes.Object_28.geometry} material={materials.material_0} position={[-0.244, 0.387, -0.131]} castShadow />
      <mesh geometry={nodes.Object_30.geometry} material={materials.material_0} position={[0, 0, -0.313]} castShadow />
      <mesh geometry={nodes.Object_32.geometry} material={materials.material_0} castShadow />
      <mesh geometry={nodes.Object_34.geometry} material={materials.material_0} position={[0, -0.375, 0]} castShadow />
      <mesh geometry={nodes.Object_37.geometry} material={materials.material_0} position={[0, 0.025, -0.125]} castShadow />
      <mesh geometry={nodes.Object_39.geometry} material={materials.material_0} position={[0, 0.025, -0.125]} castShadow />
      <mesh geometry={nodes.Object_41.geometry} material={materials.material_0} position={[0, 0.025, -0.125]} castShadow />
      <mesh geometry={nodes.Object_43.geometry} material={materials.material_0} position={[0, 0.025, -0.125]} castShadow />
      <mesh geometry={nodes.Object_45.geometry} material={materials.material_0} position={[0, 0.025, -0.125]} castShadow />
    </group>
  )
}

useGLTF.preload(modelUrl)

