/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Fixed to use scene-level rendering for reliability.

Author: okomeCraft (https://sketchfab.com/okomeCraft)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/getting-over-it-afe5643abefb4cd0bbe14c12bcd454dc
Title: 花芽すみれ / Getting Over It
*/

import { useGLTF, useAnimations } from '@react-three/drei'
import { useEffect, useRef } from 'react'
import * as THREE from 'three'
import type { Group } from 'three'

import modelUrl from '../../assets/sumire_model.glb?url'

export function SumireModel(props: React.JSX.IntrinsicElements['group']) {
  const groupRef = useRef<Group>(null)
  const { scene, animations } = useGLTF(modelUrl)
  const { actions } = useAnimations(animations, groupRef)

  scene.traverse((child) => {
    if (child instanceof THREE.Mesh) {
      child.castShadow = true
      child.receiveShadow = true
    }
  })

  useEffect(() => {
    // Play the first available animation if any
    const firstAction = Object.values(actions)[0]
    if (firstAction) {
      firstAction.reset().fadeIn(0.5).play()
    }
    return () => {
      if (firstAction) firstAction.fadeOut(0.5)
    }
  }, [actions])

  return (
    <group ref={groupRef} {...props} dispose={null}>
      <primitive object={scene} />
    </group>
  )
}

useGLTF.preload(modelUrl)
