import type * as THREE from "three";
import type { GLTF } from "three-stdlib";

export type GLTFResult = GLTF & {
  nodes: {
    Background: THREE.Mesh;
    Card: THREE.Mesh;
    Circle_FL_1: THREE.Mesh;
    BézierCurve002: THREE.Mesh;
    BézierCurve002_1: THREE.Mesh;
    BézierCurve002_2: THREE.Mesh;
    Title_F_1: THREE.Mesh;
    Plane_FR_1: THREE.Mesh;
    Cross_FL: THREE.Mesh;
    Plane_FL_1: THREE.Mesh;
    Plane_FL_2: THREE.Mesh;
    Plane_FR_2: THREE.Mesh;
    ["Plane-R-001"]: THREE.Mesh;
    Title_F_2: THREE.Mesh;
    Star_F: THREE.Mesh;
    Tri_FL_1: THREE.Mesh;
    Tri_FR_1: THREE.Mesh;
    Tri_FR_2: THREE.Mesh;
    Tri_FR_3: THREE.Mesh;
    Tri_FR_4: THREE.Mesh;
    Tri_FR_5: THREE.Mesh;
    Tri_FR_6: THREE.Mesh;
    Tri_FR_7: THREE.Mesh;
    Tri_FR_8: THREE.Mesh;
    Circle_BL_1: THREE.Mesh;
    Circle_BL_2: THREE.Mesh;
    Circle020: THREE.Mesh;
    Circle020_1: THREE.Mesh;
    Circle_BL_4: THREE.Mesh;
    Plane_BR_1: THREE.Mesh;
    Plane_BR_2: THREE.Mesh;
    Plane_BR_3: THREE.Mesh;
    Plane_BR_4: THREE.Mesh;
    Plane_BR_5: THREE.Mesh;
    Projects_Icon_1: THREE.Mesh;
    Projects_Icon_Background: THREE.Mesh;
    Projects_Icon_5: THREE.Mesh;
    Projects_Icon_6: THREE.Mesh;
    Projects_Icon_7: THREE.Mesh;
    Projects_Icon_4: THREE.Mesh;
    Projects_Icon_3: THREE.Mesh;
    Projects_Icon_2: THREE.Mesh;
    Plane034: THREE.Mesh;
    Plane034_1: THREE.Mesh;
    Projects_Info: THREE.Mesh;
    Projects_Header: THREE.Mesh;
    Plane046: THREE.Mesh;
    Plane046_1: THREE.Mesh;
    Plane046_2: THREE.Mesh;
    Plane032: THREE.Mesh;
    Plane032_1: THREE.Mesh;
    Community_Header: THREE.Mesh;
    Community_Info: THREE.Mesh;
    Plane030: THREE.Mesh;
    Plane030_1: THREE.Mesh;
    AboutMe_Icon_Background: THREE.Mesh;
    AboutMe_Icon_Avatar_1: THREE.Mesh;
    AboutMe_Icon_Avatar_2: THREE.Mesh;
    AboutMe_Header: THREE.Mesh;
    AboutMe_Info: THREE.Mesh;
    Plane035: THREE.Mesh;
    Plane035_1: THREE.Mesh;
    Plane059: THREE.Mesh;
    Plane059_1: THREE.Mesh;
    Working_Icon_1: THREE.Mesh;
    Working_Icon_2: THREE.Mesh;
    Working_Icon_3: THREE.Mesh;
    Working_Icon_4: THREE.Mesh;
    Working_Icon_6: THREE.Mesh;
    Working_Icon_8: THREE.Mesh;
    Working_Icon_5: THREE.Mesh;
    Working_Icon_7: THREE.Mesh;
    Working_Icon_9: THREE.Mesh;
    Circle022: THREE.Mesh;
    Circle022_1: THREE.Mesh;
    Working_Header: THREE.Mesh;
    Working_Info: THREE.Mesh;
    Plane033: THREE.Mesh;
    Plane033_1: THREE.Mesh;
    Circle001: THREE.Mesh;
    Circle001_1: THREE.Mesh;
    Circle001_2: THREE.Mesh;
    Awards_Info: THREE.Mesh;
    Awards_Header: THREE.Mesh;
    Plane036: THREE.Mesh;
    Plane036_1: THREE.Mesh;
    Education_Header: THREE.Mesh;
    Education_Info: THREE.Mesh;
    Plane007: THREE.Mesh;
    Plane007_1: THREE.Mesh;
    Plane007_2: THREE.Mesh;
  };
  materials: {
    ["Light Yellow"]: THREE.MeshStandardMaterial;
    ["Wood 124"]: THREE.MeshStandardMaterial;
    ["Dark Blue"]: THREE.MeshStandardMaterial;
    Yellow: THREE.MeshStandardMaterial;
    Red: THREE.MeshStandardMaterial;
  };
};

export type ModelNodes = GLTFResult["nodes"];
export type ModelMaterials = GLTFResult["materials"];

export interface SectionProps {
  nodes: ModelNodes;
  materials: ModelMaterials;
}
